### ISSUE TITLE
Fail to build MacOS version

### ISSUE THREAD

**Issue by falcon4ever** [TensorWorks/UnrealGDAL#1]
Hi,

since the release page unfortunately only contains binaries for Windows and Linux, I was attempting to build the plugin on MacOS from the source.

Installing ue4cli and conan-ue4cli was easy thanks to Brew.

When trying to run the command:
`ue4 conan build "gdal-ue4==2.4.0" "mergetiff-ue4==0.0.6"`

The command fails on the dependencies:
```
ERROR: Failed requirement 'libcurl/ue4@adamrehn/4.26' from 'gdal-ue4/2.4.0@adamrehn/4.26'
ERROR: Unable to find 'libcurl/ue4@adamrehn/4.26' in remotes
```

Any ideas what I can try? Looking at https://github.com/adamrehn/ue4-conan-recipes i don't see libcurl and looking at https://github.com/adamrehn/ue4-conan-recipes/blob/master/gdal-ue4/2.4.0/conanfile.py I think I might need: libcurl, UElibPNG and zlib too.

Full output:
```
falcon4@retro temp % ue4 conan build "gdal-ue4==2.4.0" "mergetiff-ue4==0.0.6"
Using user-specified engine root: /Users/Shared/Epic Games/UE_4.26
Using default profile for host platform "ue4.26-Mac"
Exporting package recipes from the following source directories:
- /Users/falcon4/.config/conan-ue4cli/recipes
- /Users/falcon4/Unreal/Github/temp

Exporting recipe for package "grpc-ue4/1.16.0@adamrehn/4.26"...
['conan', 'export', '/Users/falcon4/.config/conan-ue4cli/recipes/grpc-ue4/1.16.0/conanfile.py', 'grpc-ue4/1.16.0@adamrehn/4.26']
Exporting package recipe
grpc-ue4/1.16.0@adamrehn/4.26 exports: Copied 3 '.py' files: conanfile.py, __init__.py, grpc_helper.py
grpc-ue4/1.16.0@adamrehn/4.26: The stored package has not changed
grpc-ue4/1.16.0@adamrehn/4.26: Exported revision: da3287bcba9efc9a1c6b1ee0b5fc9492
Exporting recipe for package "grpc-ue4/1.30.2@adamrehn/4.26"...
['conan', 'export', '/Users/falcon4/.config/conan-ue4cli/recipes/grpc-ue4/1.30.2/conanfile.py', 'grpc-ue4/1.30.2@adamrehn/4.26']
Exporting package recipe
grpc-ue4/1.30.2@adamrehn/4.26 exports: Copied 3 '.py' files: conanfile.py, __init__.py, grpc_helper.py
grpc-ue4/1.30.2@adamrehn/4.26: The stored package has not changed
grpc-ue4/1.30.2@adamrehn/4.26: Exported revision: 92b7eb0acaa69cafd8abf4e36ae49811
Exporting recipe for package "playfab-gsdk-ue4/0.6.190103@adamrehn/4.26"...
['conan', 'export', '/Users/falcon4/.config/conan-ue4cli/recipes/playfab-gsdk-ue4/0.6.190103/conanfile.py', 'playfab-gsdk-ue4/0.6.190103@adamrehn/4.26']
Exporting package recipe
playfab-gsdk-ue4/0.6.190103@adamrehn/4.26 exports_sources: Copied 1 '.txt' file: CMakeLists.txt
playfab-gsdk-ue4/0.6.190103@adamrehn/4.26: The stored package has not changed
playfab-gsdk-ue4/0.6.190103@adamrehn/4.26: Exported revision: 434c5c7b5cb057e31bfcb4f5601705bf
Exporting recipe for package "proj-ue4/4.9.3@adamrehn/4.26"...
['conan', 'export', '/Users/falcon4/.config/conan-ue4cli/recipes/proj-ue4/4.9.3/conanfile.py', 'proj-ue4/4.9.3@adamrehn/4.26']
Exporting package recipe
proj-ue4/4.9.3@adamrehn/4.26: The stored package has not changed
proj-ue4/4.9.3@adamrehn/4.26: Exported revision: 7c259b2dd130d0a9095bad11e159db2d
Exporting recipe for package "protobuf-ue4/3.12.3@adamrehn/4.26"...
['conan', 'export', '/Users/falcon4/.config/conan-ue4cli/recipes/protobuf-ue4/3.12.3/conanfile.py', 'protobuf-ue4/3.12.3@adamrehn/4.26']
Exporting package recipe
protobuf-ue4/3.12.3@adamrehn/4.26: The stored package has not changed
protobuf-ue4/3.12.3@adamrehn/4.26: Exported revision: 400570516b73f9834883d70f771161f5
Exporting recipe for package "protobuf-ue4/3.6.1@adamrehn/4.26"...
['conan', 'export', '/Users/falcon4/.config/conan-ue4cli/recipes/protobuf-ue4/3.6.1/conanfile.py', 'protobuf-ue4/3.6.1@adamrehn/4.26']
Exporting package recipe
protobuf-ue4/3.6.1@adamrehn/4.26: The stored package has not changed
protobuf-ue4/3.6.1@adamrehn/4.26: Exported revision: 0a22da5916fec7197a0040769a492a41
Exporting recipe for package "MediaIPC-ue4/0.0.2@adamrehn/4.26"...
['conan', 'export', '/Users/falcon4/.config/conan-ue4cli/recipes/MediaIPC-ue4/0.0.2/conanfile.py', 'MediaIPC-ue4/0.0.2@adamrehn/4.26']
Exporting package recipe
MediaIPC-ue4/0.0.2@adamrehn/4.26: The stored package has not changed
MediaIPC-ue4/0.0.2@adamrehn/4.26: Exported revision: b4d1fa457e93fdcf3cb89b6c4b1f39cc
Exporting recipe for package "python-ue4/3.6.8@adamrehn/4.26"...
['conan', 'export', '/Users/falcon4/.config/conan-ue4cli/recipes/python-ue4/3.6.8/conanfile.py', 'python-ue4/3.6.8@adamrehn/4.26']
Exporting package recipe
python-ue4/3.6.8@adamrehn/4.26: The stored package has not changed
python-ue4/3.6.8@adamrehn/4.26: Exported revision: 4b8d92e06fd5a0a93dcd2aeb6f2bbde4
Exporting recipe for package "mergetiff-ue4/0.0.6@adamrehn/4.26"...
['conan', 'export', '/Users/falcon4/.config/conan-ue4cli/recipes/mergetiff-ue4/0.0.6/conanfile.py', 'mergetiff-ue4/0.0.6@adamrehn/4.26']
Exporting package recipe
mergetiff-ue4/0.0.6@adamrehn/4.26: The stored package has not changed
mergetiff-ue4/0.0.6@adamrehn/4.26: Exported revision: c1c6f72cbabb059c2450415ab73c1a54
Exporting recipe for package "geos-ue4/3.6.3@adamrehn/4.26"...
['conan', 'export', '/Users/falcon4/.config/conan-ue4cli/recipes/geos-ue4/3.6.3/conanfile.py', 'geos-ue4/3.6.3@adamrehn/4.26']
Exporting package recipe
geos-ue4/3.6.3@adamrehn/4.26: The stored package has not changed
geos-ue4/3.6.3@adamrehn/4.26: Exported revision: c6a9297c67094bc3469f5c39db5bc748
Exporting recipe for package "gdal-ue4/2.4.0@adamrehn/4.26"...
['conan', 'export', '/Users/falcon4/.config/conan-ue4cli/recipes/gdal-ue4/2.4.0/conanfile.py', 'gdal-ue4/2.4.0@adamrehn/4.26']
Exporting package recipe
gdal-ue4/2.4.0@adamrehn/4.26: The stored package has not changed
gdal-ue4/2.4.0@adamrehn/4.26: Exported revision: e6ae24e2517380547508e54ee68c587f
Exporting recipe for package "cares-ue4/1.16.1@adamrehn/4.26"...
['conan', 'export', '/Users/falcon4/.config/conan-ue4cli/recipes/cares-ue4/1.16.1/conanfile.py', 'cares-ue4/1.16.1@adamrehn/4.26']
Exporting package recipe
cares-ue4/1.16.1@adamrehn/4.26: The stored package has not changed
cares-ue4/1.16.1@adamrehn/4.26: Exported revision: c5d76be28af38b524a7d5c905d0d8326
Exporting recipe for package "cares-ue4/1.13.0@adamrehn/4.26"...
['conan', 'export', '/Users/falcon4/.config/conan-ue4cli/recipes/cares-ue4/1.13.0/conanfile.py', 'cares-ue4/1.13.0@adamrehn/4.26']
Exporting package recipe
cares-ue4/1.13.0@adamrehn/4.26: The stored package has not changed
cares-ue4/1.13.0@adamrehn/4.26: Exported revision: e88d6c749d3f4398eb0e18d16d3fe155
The following packages will be built:
- gdal-ue4/2.4.0
- mergetiff-ue4/0.0.6

Building package "gdal-ue4/2.4.0@adamrehn/4.26"...
['conan', 'install', 'gdal-ue4/2.4.0@adamrehn/4.26', '--profile=ue4.26-Mac', '--build=missing']
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=12.0
os=Macos
os_build=Macos
[options]
[build_requires]
[env]
UNREAL_ENGINE_VERSION=4.26
libcurl/ue4@adamrehn/4.26: Not found in local cache, looking in remotes...
libcurl/ue4@adamrehn/4.26: Trying with 'conan-center'...
ERROR: Failed requirement 'libcurl/ue4@adamrehn/4.26' from 'gdal-ue4/2.4.0@adamrehn/4.26'
ERROR: Unable to find 'libcurl/ue4@adamrehn/4.26' in remotes
Traceback (most recent call last):
  File "/Users/falcon4/.pyenv/versions/3.8.5/bin/ue4", line 8, in <module>
    sys.exit(main())
  File "/Users/falcon4/.pyenv/versions/3.8.5/lib/python3.8/site-packages/ue4cli/cli.py", line 222, in main
    SUPPORTED_COMMANDS[command]['action'](manager, args)
  File "/Users/falcon4/.pyenv/versions/3.8.5/lib/python3.8/site-packages/conan_ue4cli/main.py", line 48, in main
    SUBCOMMANDS[subcommand]['function'](manager, args[1:])
  File "/Users/falcon4/.pyenv/versions/3.8.5/lib/python3.8/site-packages/conan_ue4cli/commands/build.py", line 130, in build
    builder.build(name, version, args.options if args.options is not None else [])
  File "/Users/falcon4/.pyenv/versions/3.8.5/lib/python3.8/site-packages/conan_ue4cli/common/PackageBuilder.py", line 45, in build
    self._executor.execute(command, cwd=tempDir, check=True)
  File "/Users/falcon4/.pyenv/versions/3.8.5/lib/python3.8/site-packages/conan_ue4cli/common/CommandExecutor.py", line 19, in execute
    return subprocess.run(command, **kwargs).returncode == 0
  File "/Users/falcon4/.pyenv/versions/3.8.5/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['conan', 'install', 'gdal-ue4/2.4.0@adamrehn/4.26', '--profile=ue4.26-Mac', '--build=missing']' returned non-zero exit status 1.

```

**Comment by iwer** [comment]
libcurl, UElibPNG and zlib should be in the UE4 third-party libraries (Engine/Source/ThirdParty) in source builds.
Did you generate the conan wrapper packages for your UE4 installation with the cloned UE4 source before switching to the installed UE4?

https://docs.adamrehn.com/conan-ue4cli/workflow/installation#generating-conan-profiles-and-wrapper-packages

**Comment by falcon4ever** [comment]
@iwer Thanks 🤦‍♂️! Yesterday I did get to that part of the documentation but instead used the instructions for "If you are using a source build of the Unreal Engine"  (while I have the Installed build locally).

Ultimate goal is to get your GeotiffLandscape plugin 👍 working on my Mac :)!

*edit*
After doing the above, there are a few other roadblocks, you'll need to install the following from homebrew as well: 
- cmake 
- autoconf, automake, libtool (autotools)

It will then fail at:
```g++ -std=c++11 -c -DHAVE_LIBJPEG -I../jpeg/libjpeg -DPCIDSK_INTERNAL -Isdk  -DGNM_ENABLED -I/Users/falcon4/.conan/data/geos-ue4/3.6.3/adamrehn/4.26/package/4d744873e936b8ac748f7b1382e75e61a0ba8b92/include -I/Users/falcon4/.conan/data/proj-ue4/4.9.3/adamrehn/4.26/package/4d744873e936b8ac748f7b1382e75e61a0ba8b92/include -I/Users/falcon4/.conan/data/UElibPNG/ue4/adamrehn/4.26/package/de1eac9bac7a53cf4fee1104c10a77ebe6195e7d/include -I/Users/falcon4/.conan/data/zlib/ue4/adamrehn/4.26/package/de1eac9bac7a53cf4fee1104c10a77ebe6195e7d/include -DWITH_LIBPNG_1_6=0 -DWITH_LIBCURL=1 -DNDEBUG -I/Users/falcon4/.conan/data/gdal-ue4/2.4.0/adamrehn/4.26/build/b7b5c88baf382dffbd9bd7a5b0f531d62b770669/gdal/gdal/port -I/Users/falcon4/.conan/data/UElibPNG/ue4/adamrehn/4.26/package/de1eac9bac7a53cf4fee1104c10a77ebe6195e7d -I/Users/falcon4/.conan/data/UElibPNG/ue4/adamrehn/4.26/package/de1eac9bac7a53cf4fee1104c10a77ebe6195e7d/include -I/Users/falcon4/.conan/data/zlib/ue4/adamrehn/4.26/package/de1eac9bac7a53cf4fee1104c10a77ebe6195e7d -I/Users/falcon4/.conan/data/zlib/ue4/adamrehn/4.26/package/de1eac9bac7a53cf4fee1104c10a77ebe6195e7d/include  -DGDAL_COMPILATION -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -DHAVE_SSE_AT_COMPILE_TIME -m64 -O3 -stdlib=libc++ -fPIC  -Wall -Wextra -Winit-self -Wunused-parameter -Wformat -Werror=format-security -Wno-format-nonliteral -Wshorten-64-to-32 -Wshadow -Werror=vla -Wdate-time -Wnull-dereference -Wextra-semi -Wcomma -Wfloat-conversion -Wdocumentation -Wno-documentation-deprecated-sync -Wunused-private-field -Wmissing-prototypes -Wmissing-declarations -Wnon-virtual-dtor -Woverloaded-virtual -fno-operator-names -Wzero-as-null-pointer-constant -Wimplicit-fallthrough  sdk/segment/cpcidsk_array.cpp -o ../o/cpcidsk_array.o
g++ -std=c++11 -c -DHAVE_LIBJPEG -I../jpeg/libjpeg -DPCIDSK_INTERNAL -Isdk  -DGNM_ENABLED -I/Users/falcon4/.conan/data/geos-ue4/3.6.3/adamrehn/4.26/package/4d744873e936b8ac748f7b1382e75e61a0ba8b92/include -I/Users/falcon4/.conan/data/proj-ue4/4.9.3/adamrehn/4.26/package/4d744873e936b8ac748f7b1382e75e61a0ba8b92/include -I/Users/falcon4/.conan/data/UElibPNG/ue4/adamrehn/4.26/package/de1eac9bac7a53cf4fee1104c10a77ebe6195e7d/include -I/Users/falcon4/.conan/data/zlib/ue4/adamrehn/4.26/package/de1eac9bac7a53cf4fee1104c10a77ebe6195e7d/include -DWITH_LIBPNG_1_6=0 -DWITH_LIBCURL=1 -DNDEBUG -I/Users/falcon4/.conan/data/gdal-ue4/2.4.0/adamrehn/4.26/build/b7b5c88baf382dffbd9bd7a5b0f531d62b770669/gdal/gdal/port -I/Users/falcon4/.conan/data/UElibPNG/ue4/adamrehn/4.26/package/de1eac9bac7a53cf4fee1104c10a77ebe6195e7d -I/Users/falcon4/.conan/data/UElibPNG/ue4/adamrehn/4.26/package/de1eac9bac7a53cf4fee1104c10a77ebe6195e7d/include -I/Users/falcon4/.conan/data/zlib/ue4/adamrehn/4.26/package/de1eac9bac7a53cf4fee1104c10a77ebe6195e7d -I/Users/falcon4/.conan/data/zlib/ue4/adamrehn/4.26/package/de1eac9bac7a53cf4fee1104c10a77ebe6195e7d/include  -DGDAL_COMPILATION -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -DHAVE_SSE_AT_COMPILE_TIME -m64 -O3 -stdlib=libc++ -fPIC  -Wall -Wextra -Winit-self -Wunused-parameter -Wformat -Werror=format-security -Wno-format-nonliteral -Wshorten-64-to-32 -Wshadow -Werror=vla -Wdate-time -Wnull-dereference -Wextra-semi -Wcomma -Wfloat-conversion -Wdocumentation -Wno-documentation-deprecated-sync -Wunused-private-field -Wmissing-prototypes -Wmissing-declarations -Wnon-virtual-dtor -Woverloaded-virtual -fno-operator-names -Wzero-as-null-pointer-constant -Wimplicit-fallthrough  sdk/segment/cpcidskephemerissegment.cpp -o ../o/cpcidskephemerissegment.o
g++ -std=c++11 -c -DHAVE_LIBJPEG -I../jpeg/libjpeg -DPCIDSK_INTERNAL -Isdk  -DGNM_ENABLED -I/Users/falcon4/.conan/data/geos-ue4/3.6.3/adamrehn/4.26/package/4d744873e936b8ac748f7b1382e75e61a0ba8b92/include -I/Users/falcon4/.conan/data/proj-ue4/4.9.3/adamrehn/4.26/package/4d744873e936b8ac748f7b1382e75e61a0ba8b92/include -I/Users/falcon4/.conan/data/UElibPNG/ue4/adamrehn/4.26/package/de1eac9bac7a53cf4fee1104c10a77ebe6195e7d/include -I/Users/falcon4/.conan/data/zlib/ue4/adamrehn/4.26/package/de1eac9bac7a53cf4fee1104c10a77ebe6195e7d/include -DWITH_LIBPNG_1_6=0 -DWITH_LIBCURL=1 -DNDEBUG -I/Users/falcon4/.conan/data/gdal-ue4/2.4.0/adamrehn/4.26/build/b7b5c88baf382dffbd9bd7a5b0f531d62b770669/gdal/gdal/port -I/Users/falcon4/.conan/data/UElibPNG/ue4/adamrehn/4.26/package/de1eac9bac7a53cf4fee1104c10a77ebe6195e7d -I/Users/falcon4/.conan/data/UElibPNG/ue4/adamrehn/4.26/package/de1eac9bac7a53cf4fee1104c10a77ebe6195e7d/include -I/Users/falcon4/.conan/data/zlib/ue4/adamrehn/4.26/package/de1eac9bac7a53cf4fee1104c10a77ebe6195e7d -I/Users/falcon4/.conan/data/zlib/ue4/adamrehn/4.26/package/de1eac9bac7a53cf4fee1104c10a77ebe6195e7d/include  -DGDAL_COMPILATION -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -DHAVE_SSE_AT_COMPILE_TIME -m64 -O3 -stdlib=libc++ -fPIC  -Wall -Wextra -Winit-self -Wunused-parameter -Wformat -Werror=format-security -Wno-format-nonliteral -Wshorten-64-to-32 -Wshadow -Werror=vla -Wdate-time -Wnull-dereference -Wextra-semi -Wcomma -Wfloat-conversion -Wdocumentation -Wno-documentation-deprecated-sync -Wunused-private-field -Wmissing-prototypes -Wmissing-declarations -Wnon-virtual-dtor -Woverloaded-virtual -fno-operator-names -Wzero-as-null-pointer-constant -Wimplicit-fallthrough  sdk/segment/cpcidskads40model.cpp -o ../o/cpcidskads40model.o
gdal-ue4/2.4.0@adamrehn/4.26: 
gdal-ue4/2.4.0@adamrehn/4.26: ERROR: Package 'b7b5c88baf382dffbd9bd7a5b0f531d62b770669' build failed
gdal-ue4/2.4.0@adamrehn/4.26: WARN: Build folder /Users/falcon4/.conan/data/gdal-ue4/2.4.0/adamrehn/4.26/build/b7b5c88baf382dffbd9bd7a5b0f531d62b770669
ERROR: gdal-ue4/2.4.0@adamrehn/4.26: Error in build() method, line 131
	self.build_unix()
while calling 'build_unix', line 244
	autotools.make(args=["-j{}".format(tools.cpu_count())])
	ConanException: Error 2 while executing make '-j8'
Traceback (most recent call last):
  File "/Users/falcon4/.pyenv/versions/3.8.5/bin/ue4", line 8, in <module>
    sys.exit(main())
  File "/Users/falcon4/.pyenv/versions/3.8.5/lib/python3.8/site-packages/ue4cli/cli.py", line 222, in main
    SUPPORTED_COMMANDS[command]['action'](manager, args)
  File "/Users/falcon4/.pyenv/versions/3.8.5/lib/python3.8/site-packages/conan_ue4cli/main.py", line 48, in main
    SUBCOMMANDS[subcommand]['function'](manager, args[1:])
  File "/Users/falcon4/.pyenv/versions/3.8.5/lib/python3.8/site-packages/conan_ue4cli/commands/build.py", line 130, in build
    builder.build(name, version, args.options if args.options is not None else [])
  File "/Users/falcon4/.pyenv/versions/3.8.5/lib/python3.8/site-packages/conan_ue4cli/common/PackageBuilder.py", line 45, in build
    self._executor.execute(command, cwd=tempDir, check=True)
  File "/Users/falcon4/.pyenv/versions/3.8.5/lib/python3.8/site-packages/conan_ue4cli/common/CommandExecutor.py", line 19, in execute
    return subprocess.run(command, **kwargs).returncode == 0
  File "/Users/falcon4/.pyenv/versions/3.8.5/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['conan', 'install', 'gdal-ue4/2.4.0@adamrehn/4.26', '--profile=ue4.26-Mac', '--build=missing']' returned non-zero exit status 1.```

**Comment by iwer** [comment]
Hm, I'm afraid I can't help with MacOS specifics but it seems `make -j8` returns 2 which indicates an error in the Makefile. Maybe the conan recipe is missing some MacOS specific build steps in `def build_unix(self)`? 
For os=Linux f.e. there is a [patch removing iconv support](https://github.com/adamrehn/ue4-conan-recipes/blob/master/gdal-ue4/2.4.0/conanfile.py#L225) from gdal before building because the bundled toolchain doesn't supports it but i don't know if there is a bundled UE4 toolchain for MacOS.

I'd try to cd to the build directory
/Users/falcon4/.conan/data/gdal-ue4/2.4.0/adamrehn/4.26/build/b7b5c88baf382dffbd9bd7a5b0f531d62b770669/**gdal/gdal**

and see what `make` is complaining about. Also `./autoconf.sh` could provide some clues.

**Comment by falcon4ever** [comment]
@iwer thanks for the suggestions!

Yeah, there is something going wrong while it's trying to build gdal itself. I'll see if I can get it to build later. 

I switched to my Windows machine and the binaries work fine with UE4-4.26 so I will use that as my work around for now.

**Comment by falcon4ever** [comment]
Workaround:

1. Open /Users/{Username}/.config/conan-ue4cli/recipes/gdal-ue4/2.4.0/conanfile.py
2. patch/change the locally cached recipe

def source(self):
        self.run("git clone --progress --depth=1 https://github.com/OSGeo/gdal.git -b v{}".format(self.version))

to:

def source(self):
        self.run("git clone --progress --depth=1 https://github.com/falcon4ever/gdal.git -b v{}".format(self.version) + "-macosx-xcode12")

3. You should now able to build the files:
ue4 conan build "gdal-ue4==2.4.0" "mergetiff-ue4==0.0.6"


Notes:
libjson seem to cause the failure with xcode 12
see my patch here: https://github.com/falcon4ever/gdal/commit/17ee0abad6b297837ec055a9518c79d96f0628dd

**Comment by falcon4ever** [comment]
In case others are trying to get it to work on Mac OS X Catalina + Xcode 12. Here are the required changes:

1. Open /Users/{Username}/.config/conan-ue4cli/recipes/gdal-ue4/2.4.0/conanfile.py
2. Patch the locally cached recipe with these changes https://github.com/falcon4ever/ue4-conan-recipes/commit/e611c1c15038d812c6d8ed5ff3edba9227780c6e
3. You should now able to build the files:
`ue4 conan build "gdal-ue4==2.4.0" "mergetiff-ue4==0.0.6"`
4. (Optional) go to the folder `{MyProject}/Plugins/UnrealGDAL/Source/GDAL` and run:
`ue4 conan precompute ue4.26-Mac`

Notes:
libjson seem to cause the failure with xcode 12
see my patch here: falcon4ever/gdal@17ee0ab (the conanfile above points to my branch)

**Comment by adamrehn** [comment]
Apologies for being late to the party on this one guys. @falcon4ever thanks for your work patching both GDAL itself and the recipe for it. Could you please create a pull request on the [ue4-conan-recipes](https://github.com/adamrehn/ue4-conan-recipes) repository with your modified recipe? The one thing I'd suggest is to make the recipe clone the upstream GDAL repository and programmatically apply your patch, rather than cloning your fork, since patching broken things in source trees is well within the scope of a Conan recipe.

**Comment by falcon4ever** [comment]
@adamrehn Thanks! As a UE4 (and especially plugin) novice, I wasn't sure what the best approach was to document the changes, hence the forks. I'll work on creating a PR for you when I find a spare moment

Done:
https://github.com/adamrehn/ue4-conan-recipes/pull/4
