### ISSUE TITLE
Can't compile plugin with version Unreal 4.27 (ERROR: HTTPSConnectionPool... ) 

### ISSUE THREAD

**Issue by MrYako** [TensorWorks/UnrealGDAL#5]
I am download and install ue4cli and ue4 conan then I started installing the plugin from source on UnrealEngine 4.27 and  met with an error:
```bash
C:\Users\Yako>ue4 conan build "gdal-ue4==2.4.0" "mergetiff-ue4==0.0.6"
Using user-specified engine root: C:\Program Files\UnrealEngine
Using default profile for host platform "ue4.27-Win64"
Exporting package recipes from the following source directories:
- C:\Users\Yako\AppData\Roaming\conan-ue4cli\recipes
- C:\Users\Yako

Exporting recipe for package "cares-ue4/1.13.0@adamrehn/4.27"...
['conan', 'export', 'C:\\Users\\Yako\\AppData\\Roaming\\conan-ue4cli\\recipes\\cares-ue4\\1.13.0\\conanfile.py', 'cares-ue4/1.13.0@adamrehn/4.27']
Exporting package recipe
cares-ue4/1.13.0@adamrehn/4.27: The stored package has not changed
cares-ue4/1.13.0@adamrehn/4.27: Exported revision: e88d6c749d3f4398eb0e18d16d3fe155
Exporting recipe for package "cares-ue4/1.16.1@adamrehn/4.27"...
['conan', 'export', 'C:\\Users\\Yako\\AppData\\Roaming\\conan-ue4cli\\recipes\\cares-ue4\\1.16.1\\conanfile.py', 'cares-ue4/1.16.1@adamrehn/4.27']
Exporting package recipe
cares-ue4/1.16.1@adamrehn/4.27: The stored package has not changed
cares-ue4/1.16.1@adamrehn/4.27: Exported revision: c5d76be28af38b524a7d5c905d0d8326
Exporting recipe for package "gdal-ue4/2.4.0@adamrehn/4.27"...
['conan', 'export', 'C:\\Users\\Yako\\AppData\\Roaming\\conan-ue4cli\\recipes\\gdal-ue4\\2.4.0\\conanfile.py', 'gdal-ue4/2.4.0@adamrehn/4.27']
Exporting package recipe
gdal-ue4/2.4.0@adamrehn/4.27: The stored package has not changed
gdal-ue4/2.4.0@adamrehn/4.27: Exported revision: f4199bb3df9a84dd427bd99ab142d95d
Exporting recipe for package "geos-ue4/3.6.3@adamrehn/4.27"...
['conan', 'export', 'C:\\Users\\Yako\\AppData\\Roaming\\conan-ue4cli\\recipes\\geos-ue4\\3.6.3\\conanfile.py', 'geos-ue4/3.6.3@adamrehn/4.27']
Exporting package recipe
geos-ue4/3.6.3@adamrehn/4.27: The stored package has not changed
geos-ue4/3.6.3@adamrehn/4.27: Exported revision: c6a9297c67094bc3469f5c39db5bc748
Exporting recipe for package "grpc-ue4/1.16.0@adamrehn/4.27"...
['conan', 'export', 'C:\\Users\\Yako\\AppData\\Roaming\\conan-ue4cli\\recipes\\grpc-ue4\\1.16.0\\conanfile.py', 'grpc-ue4/1.16.0@adamrehn/4.27']
Exporting package recipe
grpc-ue4/1.16.0@adamrehn/4.27 exports: Copied 3 '.py' files: conanfile.py, grpc_helper.py, __init__.py
grpc-ue4/1.16.0@adamrehn/4.27: The stored package has not changed
grpc-ue4/1.16.0@adamrehn/4.27: Exported revision: da3287bcba9efc9a1c6b1ee0b5fc9492
Exporting recipe for package "grpc-ue4/1.30.2@adamrehn/4.27"...
['conan', 'export', 'C:\\Users\\Yako\\AppData\\Roaming\\conan-ue4cli\\recipes\\grpc-ue4\\1.30.2\\conanfile.py', 'grpc-ue4/1.30.2@adamrehn/4.27']
Exporting package recipe
grpc-ue4/1.30.2@adamrehn/4.27 exports: Copied 3 '.py' files: conanfile.py, grpc_helper.py, __init__.py
grpc-ue4/1.30.2@adamrehn/4.27: The stored package has not changed
grpc-ue4/1.30.2@adamrehn/4.27: Exported revision: f26cd90937712439c2abde80ef6d04de
Exporting recipe for package "grpc-ue4/1.42.0@adamrehn/4.27"...
['conan', 'export', 'C:\\Users\\Yako\\AppData\\Roaming\\conan-ue4cli\\recipes\\grpc-ue4\\1.42.0\\conanfile.py', 'grpc-ue4/1.42.0@adamrehn/4.27']
Exporting package recipe
grpc-ue4/1.42.0@adamrehn/4.27 exports: Copied 3 '.py' files: conanfile.py, grpc_helper.py, __init__.py
grpc-ue4/1.42.0@adamrehn/4.27: The stored package has not changed
grpc-ue4/1.42.0@adamrehn/4.27: Exported revision: 514f72ee6fb19bd9c6e5e79b87e0dbe9
Exporting recipe for package "MediaIPC-ue4/0.0.2@adamrehn/4.27"...
['conan', 'export', 'C:\\Users\\Yako\\AppData\\Roaming\\conan-ue4cli\\recipes\\MediaIPC-ue4\\0.0.2\\conanfile.py', 'MediaIPC-ue4/0.0.2@adamrehn/4.27']
Exporting package recipe
MediaIPC-ue4/0.0.2@adamrehn/4.27: The stored package has not changed
MediaIPC-ue4/0.0.2@adamrehn/4.27: Exported revision: 7e9dcecc38135356e588343e28a1bc91
Exporting recipe for package "mergetiff-ue4/0.0.6@adamrehn/4.27"...
['conan', 'export', 'C:\\Users\\Yako\\AppData\\Roaming\\conan-ue4cli\\recipes\\mergetiff-ue4\\0.0.6\\conanfile.py', 'mergetiff-ue4/0.0.6@adamrehn/4.27']
Exporting package recipe
mergetiff-ue4/0.0.6@adamrehn/4.27: The stored package has not changed
mergetiff-ue4/0.0.6@adamrehn/4.27: Exported revision: c1c6f72cbabb059c2450415ab73c1a54
Exporting recipe for package "playfab-gsdk-ue4/0.6.190103@adamrehn/4.27"...
['conan', 'export', 'C:\\Users\\Yako\\AppData\\Roaming\\conan-ue4cli\\recipes\\playfab-gsdk-ue4\\0.6.190103\\conanfile.py', 'playfab-gsdk-ue4/0.6.190103@adamrehn/4.27']
Exporting package recipe
playfab-gsdk-ue4/0.6.190103@adamrehn/4.27 exports_sources: Copied 1 '.txt' file: CMakeLists.txt
playfab-gsdk-ue4/0.6.190103@adamrehn/4.27: The stored package has not changed
playfab-gsdk-ue4/0.6.190103@adamrehn/4.27: Exported revision: 434c5c7b5cb057e31bfcb4f5601705bf
Exporting recipe for package "proj-ue4/4.9.3@adamrehn/4.27"...
['conan', 'export', 'C:\\Users\\Yako\\AppData\\Roaming\\conan-ue4cli\\recipes\\proj-ue4\\4.9.3\\conanfile.py', 'proj-ue4/4.9.3@adamrehn/4.27']
Exporting package recipe
proj-ue4/4.9.3@adamrehn/4.27: The stored package has not changed
proj-ue4/4.9.3@adamrehn/4.27: Exported revision: 7c259b2dd130d0a9095bad11e159db2d
Exporting recipe for package "protobuf-ue4/3.12.3@adamrehn/4.27"...
['conan', 'export', 'C:\\Users\\Yako\\AppData\\Roaming\\conan-ue4cli\\recipes\\protobuf-ue4\\3.12.3\\conanfile.py', 'protobuf-ue4/3.12.3@adamrehn/4.27']
Exporting package recipe
protobuf-ue4/3.12.3@adamrehn/4.27: The stored package has not changed
protobuf-ue4/3.12.3@adamrehn/4.27: Exported revision: 400570516b73f9834883d70f771161f5
Exporting recipe for package "protobuf-ue4/3.19.1@adamrehn/4.27"...
['conan', 'export', 'C:\\Users\\Yako\\AppData\\Roaming\\conan-ue4cli\\recipes\\protobuf-ue4\\3.19.1\\conanfile.py', 'protobuf-ue4/3.19.1@adamrehn/4.27']
Exporting package recipe
protobuf-ue4/3.19.1@adamrehn/4.27: The stored package has not changed
protobuf-ue4/3.19.1@adamrehn/4.27: Exported revision: 0136836e881358d7ca170610776ecc35
Exporting recipe for package "protobuf-ue4/3.6.1@adamrehn/4.27"...
['conan', 'export', 'C:\\Users\\Yako\\AppData\\Roaming\\conan-ue4cli\\recipes\\protobuf-ue4\\3.6.1\\conanfile.py', 'protobuf-ue4/3.6.1@adamrehn/4.27']
Exporting package recipe
protobuf-ue4/3.6.1@adamrehn/4.27: The stored package has not changed
protobuf-ue4/3.6.1@adamrehn/4.27: Exported revision: 0a22da5916fec7197a0040769a492a41
Exporting recipe for package "python-ue4/3.6.8@adamrehn/4.27"...
['conan', 'export', 'C:\\Users\\Yako\\AppData\\Roaming\\conan-ue4cli\\recipes\\python-ue4\\3.6.8\\conanfile.py', 'python-ue4/3.6.8@adamrehn/4.27']
Exporting package recipe
python-ue4/3.6.8@adamrehn/4.27: The stored package has not changed
python-ue4/3.6.8@adamrehn/4.27: Exported revision: 4b8d92e06fd5a0a93dcd2aeb6f2bbde4
The following packages will be built:
- gdal-ue4/2.4.0
- mergetiff-ue4/0.0.6

Building package "gdal-ue4/2.4.0@adamrehn/4.27"...
['conan', 'install', 'gdal-ue4/2.4.0@adamrehn/4.27', '--profile=ue4.27-Win64', '--build=missing']
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]
UNREAL_ENGINE_VERSION=4.27
ERROR: HTTPSConnectionPool(host='center.conan.io', port=443): Max retries exceeded with url: /v1/ping (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))

Unable to connect to conancenter=https://center.conan.io
1. Make sure the remote is reachable or,
2. Disable it by using conan remote disable,
Then try again.
Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\ue4.exe\__main__.py", line 7, in <module>
  File "c:\python39\lib\site-packages\ue4cli\cli.py", line 222, in main
    SUPPORTED_COMMANDS[command]['action'](manager, args)
  File "c:\python39\lib\site-packages\conan_ue4cli\main.py", line 48, in main
    SUBCOMMANDS[subcommand]['function'](manager, args[1:])
  File "c:\python39\lib\site-packages\conan_ue4cli\commands\build.py", line 130, in build
    builder.build(name, version, args.options if args.options is not None else [])
  File "c:\python39\lib\site-packages\conan_ue4cli\common\PackageBuilder.py", line 45, in build
    self._executor.execute(command, cwd=tempDir, check=True)
  File "c:\python39\lib\site-packages\conan_ue4cli\common\CommandExecutor.py", line 19, in execute
    return subprocess.run(command, **kwargs).returncode == 0
  File "c:\python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['conan', 'install', 'gdal-ue4/2.4.0@adamrehn/4.27', '--profile=ue4.27-Win64', '--build=missing']' returned non-zero exit status 1.`

**Comment by JoeJoh9** [comment]
I hope you've worked it out by now, and hopefully you've worked out a more secure solution than I did, but the way I got around this was to disable SSL certification on the conancenter remote.

`conan remote remove conancenter`
`conan remote add conancenter https://center.conan.io false`

**Comment by MrYako** [comment]
i am sorry, i am complete your command and have same error( What version you build? 

> I hope you've worked it out by now, and hopefully you've worked out a more secure solution than I did, but the way I got around this was to disable SSL certification on the conancenter remote.
> 
> `conan remote remove conancenter` `conan remote add conancenter https://center.conan.io false`

**Comment by buaaCCJ** [comment]
Have you solved ？

**Comment by MrYako** [comment]
> Have you solved ？

Nope, yet

**Comment by PanopticonL** [comment]
I can't compile it too,but the error is different

`PS C:\Users\78510> ue4 conan build "gdal-ue4==2.4.0" "mergetiff-ue4==0.0.6"
Using user-specified engine root: E:\UE_4.27
Using default profile for host platform "ue4.27-Win64"
Exporting package recipes from the following source directories:
- C:\Users\78510\AppData\Roaming\conan-ue4cli\recipes
- C:\Users\78510

Exporting recipe for package "cares-ue4/1.13.0@adamrehn/4.27"...
['conan', 'export', 'C:\\Users\\78510\\AppData\\Roaming\\conan-ue4cli\\recipes\\cares-ue4\\1.13.0\\conanfile.py', 'cares-ue4/1.13.0@adamrehn/4.27']
Exporting package recipe
cares-ue4/1.13.0@adamrehn/4.27: The stored package has not changed
cares-ue4/1.13.0@adamrehn/4.27: Exported revision: e88d6c749d3f4398eb0e18d16d3fe155
Exporting recipe for package "cares-ue4/1.16.1@adamrehn/4.27"...
['conan', 'export', 'C:\\Users\\78510\\AppData\\Roaming\\conan-ue4cli\\recipes\\cares-ue4\\1.16.1\\conanfile.py', 'cares-ue4/1.16.1@adamrehn/4.27']
Exporting package recipe
cares-ue4/1.16.1@adamrehn/4.27: The stored package has not changed
cares-ue4/1.16.1@adamrehn/4.27: Exported revision: c5d76be28af38b524a7d5c905d0d8326
Exporting recipe for package "gdal-ue4/2.4.0@adamrehn/4.27"...
['conan', 'export', 'C:\\Users\\78510\\AppData\\Roaming\\conan-ue4cli\\recipes\\gdal-ue4\\2.4.0\\conanfile.py', 'gdal-ue4/2.4.0@adamrehn/4.27']
Exporting package recipe
gdal-ue4/2.4.0@adamrehn/4.27: The stored package has not changed
gdal-ue4/2.4.0@adamrehn/4.27: Exported revision: f4199bb3df9a84dd427bd99ab142d95d
Exporting recipe for package "geos-ue4/3.6.3@adamrehn/4.27"...
['conan', 'export', 'C:\\Users\\78510\\AppData\\Roaming\\conan-ue4cli\\recipes\\geos-ue4\\3.6.3\\conanfile.py', 'geos-ue4/3.6.3@adamrehn/4.27']
Exporting package recipe
geos-ue4/3.6.3@adamrehn/4.27: The stored package has not changed
geos-ue4/3.6.3@adamrehn/4.27: Exported revision: c6a9297c67094bc3469f5c39db5bc748
Exporting recipe for package "grpc-ue4/1.16.0@adamrehn/4.27"...
['conan', 'export', 'C:\\Users\\78510\\AppData\\Roaming\\conan-ue4cli\\recipes\\grpc-ue4\\1.16.0\\conanfile.py', 'grpc-ue4/1.16.0@adamrehn/4.27']
Exporting package recipe
grpc-ue4/1.16.0@adamrehn/4.27 exports: Copied 3 '.py' files: conanfile.py, grpc_helper.py, __init__.py
grpc-ue4/1.16.0@adamrehn/4.27: The stored package has not changed
grpc-ue4/1.16.0@adamrehn/4.27: Exported revision: da3287bcba9efc9a1c6b1ee0b5fc9492
Exporting recipe for package "grpc-ue4/1.30.2@adamrehn/4.27"...
['conan', 'export', 'C:\\Users\\78510\\AppData\\Roaming\\conan-ue4cli\\recipes\\grpc-ue4\\1.30.2\\conanfile.py', 'grpc-ue4/1.30.2@adamrehn/4.27']
Exporting package recipe
grpc-ue4/1.30.2@adamrehn/4.27 exports: Copied 3 '.py' files: conanfile.py, grpc_helper.py, __init__.py
grpc-ue4/1.30.2@adamrehn/4.27: The stored package has not changed
grpc-ue4/1.30.2@adamrehn/4.27: Exported revision: f26cd90937712439c2abde80ef6d04de
Exporting recipe for package "grpc-ue4/1.42.0@adamrehn/4.27"...
['conan', 'export', 'C:\\Users\\78510\\AppData\\Roaming\\conan-ue4cli\\recipes\\grpc-ue4\\1.42.0\\conanfile.py', 'grpc-ue4/1.42.0@adamrehn/4.27']
Exporting package recipe
grpc-ue4/1.42.0@adamrehn/4.27 exports: Copied 3 '.py' files: conanfile.py, grpc_helper.py, __init__.py
grpc-ue4/1.42.0@adamrehn/4.27: The stored package has not changed
grpc-ue4/1.42.0@adamrehn/4.27: Exported revision: 514f72ee6fb19bd9c6e5e79b87e0dbe9
Exporting recipe for package "MediaIPC-ue4/0.0.2@adamrehn/4.27"...
['conan', 'export', 'C:\\Users\\78510\\AppData\\Roaming\\conan-ue4cli\\recipes\\MediaIPC-ue4\\0.0.2\\conanfile.py', 'MediaIPC-ue4/0.0.2@adamrehn/4.27']
Exporting package recipe
MediaIPC-ue4/0.0.2@adamrehn/4.27: The stored package has not changed
MediaIPC-ue4/0.0.2@adamrehn/4.27: Exported revision: 7e9dcecc38135356e588343e28a1bc91
Exporting recipe for package "mergetiff-ue4/0.0.6@adamrehn/4.27"...
['conan', 'export', 'C:\\Users\\78510\\AppData\\Roaming\\conan-ue4cli\\recipes\\mergetiff-ue4\\0.0.6\\conanfile.py', 'mergetiff-ue4/0.0.6@adamrehn/4.27']
Exporting package recipe
mergetiff-ue4/0.0.6@adamrehn/4.27: The stored package has not changed
mergetiff-ue4/0.0.6@adamrehn/4.27: Exported revision: c1c6f72cbabb059c2450415ab73c1a54
Exporting recipe for package "playfab-gsdk-ue4/0.6.190103@adamrehn/4.27"...
['conan', 'export', 'C:\\Users\\78510\\AppData\\Roaming\\conan-ue4cli\\recipes\\playfab-gsdk-ue4\\0.6.190103\\conanfile.py', 'playfab-gsdk-ue4/0.6.190103@adamrehn/4.27']
Exporting package recipe
playfab-gsdk-ue4/0.6.190103@adamrehn/4.27 exports_sources: Copied 1 '.txt' file: CMakeLists.txt
playfab-gsdk-ue4/0.6.190103@adamrehn/4.27: The stored package has not changed
playfab-gsdk-ue4/0.6.190103@adamrehn/4.27: Exported revision: 434c5c7b5cb057e31bfcb4f5601705bf
Exporting recipe for package "proj-ue4/4.9.3@adamrehn/4.27"...
['conan', 'export', 'C:\\Users\\78510\\AppData\\Roaming\\conan-ue4cli\\recipes\\proj-ue4\\4.9.3\\conanfile.py', 'proj-ue4/4.9.3@adamrehn/4.27']
Exporting package recipe
proj-ue4/4.9.3@adamrehn/4.27: The stored package has not changed
proj-ue4/4.9.3@adamrehn/4.27: Exported revision: 7c259b2dd130d0a9095bad11e159db2d
Exporting recipe for package "protobuf-ue4/3.12.3@adamrehn/4.27"...
['conan', 'export', 'C:\\Users\\78510\\AppData\\Roaming\\conan-ue4cli\\recipes\\protobuf-ue4\\3.12.3\\conanfile.py', 'protobuf-ue4/3.12.3@adamrehn/4.27']
Exporting package recipe
protobuf-ue4/3.12.3@adamrehn/4.27: The stored package has not changed
protobuf-ue4/3.12.3@adamrehn/4.27: Exported revision: 400570516b73f9834883d70f771161f5
Exporting recipe for package "protobuf-ue4/3.19.1@adamrehn/4.27"...
['conan', 'export', 'C:\\Users\\78510\\AppData\\Roaming\\conan-ue4cli\\recipes\\protobuf-ue4\\3.19.1\\conanfile.py', 'protobuf-ue4/3.19.1@adamrehn/4.27']
Exporting package recipe
protobuf-ue4/3.19.1@adamrehn/4.27: The stored package has not changed
protobuf-ue4/3.19.1@adamrehn/4.27: Exported revision: 0136836e881358d7ca170610776ecc35
Exporting recipe for package "protobuf-ue4/3.6.1@adamrehn/4.27"...
['conan', 'export', 'C:\\Users\\78510\\AppData\\Roaming\\conan-ue4cli\\recipes\\protobuf-ue4\\3.6.1\\conanfile.py', 'protobuf-ue4/3.6.1@adamrehn/4.27']
Exporting package recipe
protobuf-ue4/3.6.1@adamrehn/4.27: The stored package has not changed
protobuf-ue4/3.6.1@adamrehn/4.27: Exported revision: 0a22da5916fec7197a0040769a492a41
Exporting recipe for package "python-ue4/3.6.8@adamrehn/4.27"...
['conan', 'export', 'C:\\Users\\78510\\AppData\\Roaming\\conan-ue4cli\\recipes\\python-ue4\\3.6.8\\conanfile.py', 'python-ue4/3.6.8@adamrehn/4.27']
Exporting package recipe
python-ue4/3.6.8@adamrehn/4.27: The stored package has not changed
python-ue4/3.6.8@adamrehn/4.27: Exported revision: 4b8d92e06fd5a0a93dcd2aeb6f2bbde4
The following packages will be built:
- gdal-ue4/2.4.0
- mergetiff-ue4/0.0.6

Building package "gdal-ue4/2.4.0@adamrehn/4.27"...
['conan', 'install', 'gdal-ue4/2.4.0@adamrehn/4.27', '--profile=ue4.27-Win64', '--build=missing']
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]
UNREAL_ENGINE_VERSION=4.27
libcurl/ue4@adamrehn/4.27: Not found in local cache, looking in remotes...
libcurl/ue4@adamrehn/4.27: Trying with 'conancenter'...
ERROR: Failed requirement 'libcurl/ue4@adamrehn/4.27' from 'gdal-ue4/2.4.0@adamrehn/4.27'
ERROR: Unable to find 'libcurl/ue4@adamrehn/4.27' in remotes
Traceback (most recent call last):
  File "C:\Users\78510\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\78510\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\78510\AppData\Local\Programs\Python\Python310\Scripts\ue4.exe\__main__.py", line 7, in <module>
  File "C:\Users\78510\AppData\Local\Programs\Python\Python310\lib\site-packages\ue4cli\cli.py", line 222, in main
    SUPPORTED_COMMANDS[command]['action'](manager, args)
  File "C:\Users\78510\AppData\Local\Programs\Python\Python310\lib\site-packages\conan_ue4cli\main.py", line 48, in main
    SUBCOMMANDS[subcommand]['function'](manager, args[1:])
  File "C:\Users\78510\AppData\Local\Programs\Python\Python310\lib\site-packages\conan_ue4cli\commands\build.py", line 130, in build
    builder.build(name, version, args.options if args.options is not None else [])
  File "C:\Users\78510\AppData\Local\Programs\Python\Python310\lib\site-packages\conan_ue4cli\common\PackageBuilder.py", line 45, in build
    self._executor.execute(command, cwd=tempDir, check=True)
  File "C:\Users\78510\AppData\Local\Programs\Python\Python310\lib\site-packages\conan_ue4cli\common\CommandExecutor.py", line 19, in execute
    return subprocess.run(command, **kwargs).returncode == 0
  File "C:\Users\78510\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['conan', 'install', 'gdal-ue4/2.4.0@adamrehn/4.27', '--profile=ue4.27-Win64', '--build=missing']' returned non-zero exit status 1.`

**Comment by iwer** [comment]
This has probably something to do with https://conan.bintray.com getting no more new packages after July 1st 2021: [Conan Blogpost here](https://blog.conan.io/2021/06/10/New-conan-release-1-37.html).


With these conan settings:
```
$ conan remote list
conancenter: https://center.conan.io [Verify SSL: True]
conan-center: https://conan.bintray.com [Verify SSL: True, Disabled: True]
```
I can find the libcurl module
```
$ conan search libcurl/ue4@adamrehn/4.27
Existing packages for recipe libcurl/ue4@adamrehn/4.27:

    Package_ID: 4a8aa5a92eca740ec3100060d2a1f829bb028521
        [settings]
            arch: x86_64
            build_type: Release
            compiler: clang
            compiler.libcxx: libc++
            compiler.version: 11
            os: Linux
        [requires]
            ue4lib/ue4@adamrehn/profile:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
        Outdated from recipe: False
```
hogsy9 already briefly mentioned how to change the conan repository:
> I hope you've worked it out by now, and hopefully you've worked out a more secure solution than I did, but the way I got around this was to disable SSL certification on the conancenter remote.
> 
> `conan remote remove conancenter` `conan remote add conancenter https://center.conan.io false`

**Comment by PanopticonL** [comment]
@iwer Thanks for your reply,I had try these conan setting:

 ```
 $ conan remote list
 conancenter: https://center.conan.io [Verify SSL: True]
 conan-center: https://conan.bintray.com [Verify SSL: True, Disabled: True]
 ```
But I still got:
```
conan search libcurl/ue4@adamrehn/4.27
ERROR: Recipe not found: 'libcurl/ue4@adamrehn/4.27'
```
```
ERROR: Failed requirement 'libcurl/ue4@adamrehn/4.27' from 'gdal-ue4/2.4.0@adamrehn/4.27'
ERROR: Unable to find 'libcurl/ue4@adamrehn/4.27' in remotes
```
and then I also had try these conan setting:
 ```
 $ conan remote list
 conancenter: https://center.conan.io [Verify SSL: True]
 conan-center: https://conan.bintray.com [Verify SSL: True]
 ```
then I got a different problem:
 ```
libcurl/ue4@adamrehn/4.27: Not found in local cache, looking in remotes...
libcurl/ue4@adamrehn/4.27: Trying with 'conancenter'...
libcurl/ue4@adamrehn/4.27: Trying with 'conan-center'...
libcurl/ue4@adamrehn/4.27: WARN: Remote https://conan.bintray.com is deprecated and will be shut down soon.
libcurl/ue4@adamrehn/4.27: WARN: Please use the new 'conancenter' default remote.
libcurl/ue4@adamrehn/4.27: WARN: Add it to your remotes with: conan remote add -i 0 conancenter https://center.conan.io
ERROR: Failed requirement 'libcurl/ue4@adamrehn/4.27' from 'gdal-ue4/2.4.0@adamrehn/4.27'
ERROR: HTTPSConnectionPool(host='conan.bintray.com', port=443): Max retries exceeded with url: /v1/ping (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)')))

Unable to connect to conan-center=https://conan.bintray.com
1. Make sure the remote is reachable or,
2. Disable it by using conan remote disable,
Then try again.
 ```
I also try to disable SSL certification ,but still got the same problem.

**Comment by iwer** [comment]
Wait just remembered: libcurl gets wrapped in a conan package from UE4 thirdparty libraries...
Did you by chance forget to generate the wrapper packages?
```
$ ue4 conan setroot <UE4 Root directory>
$ ue4 conan generate
...
Generating and installing wrapper package for libWebSockets...
Generating and installing wrapper package for libcurl...
Generating and installing wrapper package for libstrophe...
...
```

**Comment by PanopticonL** [comment]
@iwer Thanks for your great help again,I'm using an installed build of ue,and i don't check the generate information carefully,after i build the source code, the problem has been solved, thank you so much
